# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3908ef18c7a33eef635305be9e4b8f397397b01479ae67c822e6dcccceafafaecb457cfaa055ff19b932098b8141f734655c088abc9f89560a37f630de9e464d

test:
  secret_key_base: 7bbc9c84c117a4e06c7ba3359644ba019bf03c66a4f817137bd979583c77f93542051aa7307dcf69a1a98330bf544b7bd65db29d97b121a06e2c2bc6463d78c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
